from __future__ import annotations

from datetime import datetime, timezone

import pytest

from bsync.models import Bookmark, BookmarkFolder, BookmarkTree, SyncRecord, EPOCH_UTC

_NOW = datetime(2026, 1, 22, 7, 0, 0, tzinfo=timezone.utc)
_OLDER = datetime(2026, 1, 21, 7, 0, 0, tzinfo=timezone.utc)

# ---- Vivaldi フィクスチャ ----

VIVALDI_SIMPLE_DATA = {
    "checksum": "abcdef1234567890abcdef1234567890",
    "version": 1,
    "sync_metadata": {"token": "xxx"},
    "roots": {
        "bookmark_bar": {
            "type": "folder",
            "id": "1",
            "guid": "bar-guid-0000",
            "name": "ブックマーク バー",
            "date_added": "13413538871971562",
            "date_last_used": "0",
            "date_modified": "13413538871971562",
            "children": [
                {
                    "type": "url",
                    "id": "2",
                    "guid": "bm-guid-0001",
                    "name": "Example",
                    "url": "https://example.com",
                    "date_added": "13413538871971562",
                    "date_last_used": "0",
                    "meta_info": {"Thumbnail": "AUTOGENERATED"},
                }
            ],
        },
        "other": {
            "type": "folder",
            "id": "3",
            "guid": "other-guid-0000",
            "name": "その他のブックマーク",
            "date_added": "13413538871971562",
            "date_last_used": "0",
            "date_modified": "13413538871971562",
            "children": [],
        },
        "synced": {
            "type": "folder",
            "id": "4",
            "guid": "synced-guid-0000",
            "name": "モバイルのブックマーク",
            "date_added": "0",
            "date_last_used": "0",
            "date_modified": "0",
            "children": [],
        },
    },
}

VIVALDI_NESTED_DATA = {
    "checksum": "",
    "version": 1,
    "roots": {
        "bookmark_bar": {
            "type": "folder",
            "id": "1",
            "guid": "bar-guid-nested",
            "name": "ブックマーク バー",
            "date_added": "13413538871971562",
            "date_last_used": "0",
            "date_modified": "13413538871971562",
            "children": [
                {
                    "type": "folder",
                    "id": "2",
                    "guid": "folder-l1",
                    "name": "Work",
                    "date_added": "13413538871971562",
                    "date_last_used": "0",
                    "date_modified": "13413538871971562",
                    "children": [
                        {
                            "type": "folder",
                            "id": "3",
                            "guid": "folder-l2",
                            "name": "Dev",
                            "date_added": "13413538871971562",
                            "date_last_used": "0",
                            "date_modified": "13413538871971562",
                            "children": [
                                {
                                    "type": "url",
                                    "id": "4",
                                    "guid": "bm-nested",
                                    "name": "GitHub",
                                    "url": "https://github.com",
                                    "date_added": "13413538871971562",
                                    "date_last_used": "0",
                                    "meta_info": {},
                                }
                            ],
                        }
                    ],
                }
            ],
        },
        "other": {
            "type": "folder",
            "id": "5",
            "guid": "other-guid-nested",
            "name": "その他",
            "date_added": "0",
            "date_last_used": "0",
            "date_modified": "0",
            "children": [],
        },
        "synced": {
            "type": "folder",
            "id": "6",
            "guid": "synced-guid-nested",
            "name": "モバイル",
            "date_added": "0",
            "date_last_used": "0",
            "date_modified": "0",
            "children": [],
        },
    },
}

# ---- Safari フィクスチャ ----

SAFARI_SIMPLE_DATA = {
    "WebBookmarkFileVersion": 1,
    "WebBookmarkType": "WebBookmarkTypeList",
    "WebBookmarkUUID": "ROOT-UUID-0000",
    "Title": "",
    "Children": [
        {
            "Title": "BookmarksBar",
            "WebBookmarkType": "WebBookmarkTypeList",
            "WebBookmarkUUID": "BAR-UUID-0000",
            "Children": [
                {
                    "URLString": "https://example.com",
                    "URIDictionary": {"title": "Example"},
                    "WebBookmarkType": "WebBookmarkTypeLeaf",
                    "WebBookmarkUUID": "LEAF-UUID-0001",
                    "DateAdded": 666543210.0,
                }
            ],
        },
        {
            "Title": "BookmarksMenu",
            "WebBookmarkType": "WebBookmarkTypeList",
            "WebBookmarkUUID": "MENU-UUID-0000",
            "Children": [],
        },
        {
            "Title": "com.apple.ReadingList",
            "WebBookmarkType": "WebBookmarkTypeList",
            "WebBookmarkUUID": "RL-UUID-0000",
            "Children": [],
        },
    ],
}

SAFARI_WITH_PROXY_DATA = {
    "WebBookmarkFileVersion": 1,
    "WebBookmarkType": "WebBookmarkTypeList",
    "WebBookmarkUUID": "ROOT-UUID-PROXY",
    "Title": "",
    "Children": [
        {
            "Title": "BookmarksBar",
            "WebBookmarkType": "WebBookmarkTypeList",
            "WebBookmarkUUID": "BAR-UUID-PROXY",
            "Children": [
                {
                    "WebBookmarkType": "WebBookmarkTypeProxy",
                    "WebBookmarkUUID": "PROXY-UUID-0001",
                },
                {
                    "URLString": "https://apple.com",
                    "URIDictionary": {"title": "Apple"},
                    "WebBookmarkType": "WebBookmarkTypeLeaf",
                    "WebBookmarkUUID": "LEAF-UUID-APPLE",
                    "DateAdded": 700000000.0,
                },
            ],
        },
        {
            "Title": "BookmarksMenu",
            "WebBookmarkType": "WebBookmarkTypeList",
            "WebBookmarkUUID": "MENU-UUID-PROXY",
            "Children": [],
        },
    ],
}

# ---- スナップショット フィクスチャ ----

@pytest.fixture
def base_snapshot_empty():
    return {}


@pytest.fixture
def base_snapshot_with_example():
    return {
        "https://example.com": SyncRecord(
            url="https://example.com",
            title="Example",
            guid_vivaldi="bm-guid-0001",
            uuid_safari="LEAF-UUID-0001",
            date_added_unix=_OLDER.timestamp(),
            date_modified_unix=_OLDER.timestamp(),
            folder_path_vivaldi=["bookmark_bar"],
            folder_path_safari=["BookmarksBar"],
        )
    }


@pytest.fixture
def vivaldi_flat_example():
    return {
        "https://example.com": Bookmark(
            title="Example",
            url="https://example.com",
            guid="bm-guid-0001",
            date_added=_OLDER,
            date_modified=_OLDER,
            folder_path=["bookmark_bar"],
        )
    }


@pytest.fixture
def safari_flat_example():
    return {
        "https://example.com": Bookmark(
            title="Example",
            url="https://example.com",
            guid="LEAF-UUID-0001",
            date_added=_OLDER,
            date_modified=_OLDER,
            folder_path=["BookmarksBar"],
        )
    }


def make_bookmark(
    url: str = "https://example.com",
    title: str = "Example",
    guid: str = "test-guid",
    date_added: datetime = _OLDER,
    date_modified: datetime = _OLDER,
    folder_path: list[str] | None = None,
) -> Bookmark:
    return Bookmark(
        title=title,
        url=url,
        guid=guid,
        date_added=date_added,
        date_modified=date_modified,
        folder_path=folder_path or ["bookmark_bar"],
    )


def make_sync_record(
    url: str = "https://example.com",
    title: str = "Example",
    folder_path_vivaldi: list[str] | None = None,
    folder_path_safari: list[str] | None = None,
    date_modified_unix: float | None = None,
) -> SyncRecord:
    return SyncRecord(
        url=url,
        title=title,
        guid_vivaldi="viv-guid",
        uuid_safari="saf-guid",
        date_added_unix=_OLDER.timestamp(),
        date_modified_unix=date_modified_unix or _OLDER.timestamp(),
        folder_path_vivaldi=folder_path_vivaldi or ["bookmark_bar"],
        folder_path_safari=folder_path_safari or ["BookmarksBar"],
    )
